export const cardData = [
  {
    id: 1,
    hearts: [
      {
        id: 1,
        suit: "hearts",
        name: 2,
        value: 2,
        Image: "/images/Hearts/2.png",
      },
      {
        id: 2,
        suit: "hearts",
        name: 3,
        value: 3,
        Image: "/images/Hearts/3.png",
      },
      {
        id: 3,
        suit: "hearts",
        name: 4,
        value: 4,
        Image: "/images/Hearts/4.png",
      },
      {
        id: 4,
        suit: "hearts",
        name: 5,
        value: 5,
        Image: "/images/Hearts/5.png",
      },
      {
        id: 5,
        suit: "hearts",
        name: 6,
        value: 6,
        Image: "/images/Hearts/6.png",
      },
      {
        id: 6,
        suit: "hearts",
        name: 7,
        value: 7,
        Image: "/images/Hearts/7.png",
      },
      {
        id: 7,
        suit: "hearts",
        name: 8,
        value: 8,
        Image: "/images/Hearts/8.png",
      },
      {
        id: 8,
        suit: "hearts",
        name: 9,
        value: 9,
        Image: "/images/Hearts/9.png",
      },
      {
        id: 9,
        suit: "hearts",
        name: 10,
        value: 10,
        Image: "/images/Hearts/10.png",
      },
      {
        id: 10,
        suit: "hearts",
        name: "J",
        value: 10,
        Image: "/images/Hearts/J.png",
      },
      {
        id: 11,
        suit: "hearts",
        name: "Q",
        value: 10,
        Image: "/images/Hearts/Q.png",
      },
      {
        id: 12,
        suit: "hearts",
        name: "K",
        value: 10,
        Image: "/images/Hearts/K.png",
      },
      {
        id: 13,
        suit: "hearts",
        name: "A",
        value: 11,
        Image: "/images/Hearts/A.png",
      },
    ],
  },
  {
    id: 2,
    clubs: [
      {
        id: 1,
        suit: "clubs",
        name: 2,
        value: 2,
        Image: "/images/Clubs/2.png",
      },
      {
        id: 2,
        suit: "clubs",
        name: 3,
        value: 3,
        Image: "/images/Clubs/3.png",
      },
      {
        id: 3,
        suit: "clubs",
        name: 4,
        value: 4,
        Image: "/images/Clubs/4.png",
      },
      {
        id: 4,
        suit: "clubs",
        name: 5,
        value: 5,
        Image: "/images/Clubs/5.png",
      },
      {
        id: 5,
        suit: "clubs",
        name: 6,
        value: 6,
        Image: "/images/Clubs/6.png",
      },
      {
        id: 6,
        suit: "clubs",
        name: 7,
        value: 7,
        Image: "/images/Clubs/7.png",
      },
      {
        id: 7,
        suit: "clubs",
        name: 8,
        value: 8,
        Image: "/images/Clubs/8.png",
      },
      {
        id: 8,
        suit: "clubs",
        name: 9,
        value: 9,
        Image: "/images/Clubs/9.png",
      },
      {
        id: 9,
        suit: "clubs",
        name: 10,
        value: 10,
        Image: "/images/Clubs/10.png",
      },
      {
        id: 10,
        suit: "clubs",
        name: "J",
        value: 10,
        Image: "/images/Clubs/J.png",
      },
      {
        id: 11,
        suit: "clubs",
        name: "Q",
        value: 10,
        Image: "/images/Clubs/Q.png",
      },
      {
        id: 12,
        suit: "clubs",
        name: "K",
        value: 10,
        Image: "/images/Clubs/K.png",
      },
      {
        id: 13,
        suit: "clubs",
        name: "A",
        value: 11,
        Image: "/images/Clubs/A.png",
      },
    ],
  },
  {
    id: 3,
    diamonds: [
      {
        id: 1,
        suit: "diamonds",
        name: 2,
        value: 2,
        Image: "/images/Diamonds/2.png",
      },
      {
        id: 2,
        suit: "diamonds",
        name: 3,
        value: 3,
        Image: "/images/Diamonds/3.png",
      },
      {
        id: 3,
        suit: "diamonds",
        name: 4,
        value: 4,
        Image: "/images/Diamonds/4.png",
      },
      {
        id: 4,
        suit: "diamonds",
        name: 5,
        value: 5,
        Image: "/images/Diamonds/5.png",
      },
      {
        id: 5,
        suit: "diamonds",
        name: 6,
        value: 6,
        Image: "/images/Diamonds/6.png",
      },
      {
        id: 6,
        suit: "diamonds",
        name: 7,
        value: 7,
        Image: "/images/Diamonds/7.png",
      },
      {
        id: 7,
        suit: "diamonds",
        name: 8,
        value: 8,
        Image: "/images/Diamonds/8.png",
      },
      {
        id: 8,
        suit: "diamonds",
        name: 9,
        value: 9,
        Image: "/images/Diamonds/9.png",
      },
      {
        id: 9,
        suit: "diamonds",
        name: 10,
        value: 10,
        Image: "/images/Diamonds/10.png",
      },
      {
        id: 10,
        suit: "diamonds",
        name: "J",
        value: 10,
        Image: "/images/Diamonds/J.png",
      },
      {
        id: 11,
        suit: "diamonds",
        name: "Q",
        value: 10,
        Image: "/images/Diamonds/Q.png",
      },
      {
        id: 12,
        suit: "diamonds",
        name: "K",
        value: 10,
        Image: "/images/Diamonds/K.png",
      },
      {
        id: 13,
        suit: "diamonds",
        name: "A",
        value: 11,
        Image: "/images/Diamonds/A.png",
      },
    ],
  },
  {
    id: 4,
    spades: [
      {
        id: 1,
        suit: "spades",
        name: 2,
        value: 2,
        Image: "/images/Spades/2.png",
      },
      {
        id: 2,
        suit: "spades",
        name: 3,
        value: 3,
        Image: "/images/Spades/3.png",
      },
      {
        id: 3,
        suit: "spades",
        name: 4,
        value: 4,
        Image: "/images/Spades/4.png",
      },
      {
        id: 4,
        suit: "spades",
        name: 5,
        value: 5,
        Image: "/images/Spades/5.png",
      },
      {
        id: 5,
        suit: "spades",
        name: 6,
        value: 6,
        Image: "/images/Spades/6.png",
      },
      {
        id: 6,
        suit: "spades",
        name: 7,
        value: 7,
        Image: "/images/Spades/7.png",
      },
      {
        id: 7,
        suit: "spades",
        name: 8,
        value: 8,
        Image: "/images/Spades/8.png",
      },
      {
        id: 8,
        suit: "spades",
        name: 9,
        value: 9,
        Image: "/images/Spades/9.png",
      },
      {
        id: 9,
        suit: "spades",
        name: 10,
        value: 10,
        Image: "/images/Spades/10.png",
      },
      {
        id: 10,
        suit: "spades",
        name: "J",
        value: 10,
        Image: "/images/Spades/J.png",
      },
      {
        id: 11,
        suit: "spades",
        name: "Q",
        value: 10,
        Image: "/images/Spades/Q.png",
      },
      {
        id: 12,
        suit: "spades",
        name: "K",
        value: 10,
        Image: "/images/Spades/K.png",
      },
      {
        id: 13,
        suit: "spades",
        name: "A",
        value: 11,
        Image: "/images/Spades/A.png",
      },
    ],
  },
];
