export const cardData = [
  {
    id: 1,
    hearts: [
      {
        id: 1,
        suit: "hearts",
        name: 2,
        value: 2,
      },
      {
        id: 2,
        suit: "hearts",
        name: 3,
        value: 3,
      },
      {
        id: 3,
        suit: "hearts",
        name: 4,
        value: 4,
      },
      {
        id: 4,
        suit: "hearts",
        name: 5,
        value: 5,
      },
      {
        id: 5,
        suit: "hearts",
        name: 6,
        value: 6,
      },
      {
        id: 6,
        suit: "hearts",
        name: 7,
        value: 7,
      },
      {
        id: 7,
        suit: "hearts",
        name: 8,
        value: 8,
      },
      {
        id: 8,
        suit: "hearts",
        name: 9,
        value: 9,
      },
      {
        id: 9,
        suit: "hearts",
        name: 10,
        value: 10,
      },
      {
        id: 10,
        suit: "hearts",
        name: "J",
        value: 10,
      },
      {
        id: 11,
        suit: "hearts",
        name: "Q",
        value: 10,
      },
      {
        id: 12,
        suit: "hearts",
        name: "K",
        value: 10,
      },
      {
        id: 13,
        suit: "hearts",
        name: "A",
        value: 11,
      },
    ],
  },
  {
    id: 2,
    clubs: [
      {
        id: 1,
        suit: "clubs",
        name: 2,
        value: 2,
      },
      {
        id: 2,
        suit: "clubs",
        name: 3,
        value: 3,
      },
      {
        id: 3,
        suit: "clubs",
        name: 4,
        value: 4,
      },
      {
        id: 4,
        suit: "clubs",
        name: 5,
        value: 5,
      },
      {
        id: 5,
        suit: "clubs",
        name: 6,
        value: 6,
      },
      {
        id: 6,
        suit: "clubs",
        name: 7,
        value: 7,
      },
      {
        id: 7,
        suit: "clubs",
        name: 8,
        value: 8,
      },
      {
        id: 8,
        suit: "clubs",
        name: 9,
        value: 9,
      },
      {
        id: 9,
        suit: "clubs",
        name: 10,
        value: 10,
      },
      {
        id: 10,
        suit: "clubs",
        name: "J",
        value: 10,
      },
      {
        id: 11,
        suit: "clubs",
        name: "Q",
        value: 10,
      },
      {
        id: 12,
        suit: "clubs",
        name: "K",
        value: 10,
      },
      {
        id: 13,
        suit: "clubs",
        name: "A",
        value: 11,
      },
    ],
  },
  {
    id: 3,
    diamonds: [
      {
        id: 1,
        suit: "diamonds",
        name: 2,
        value: 2,
      },
      {
        id: 2,
        suit: "diamonds",
        name: 3,
        value: 3,
      },
      {
        id: 3,
        suit: "diamonds",
        name: 4,
        value: 4,
      },
      {
        id: 4,
        suit: "diamonds",
        name: 5,
        value: 5,
      },
      {
        id: 5,
        suit: "diamonds",
        name: 6,
        value: 6,
      },
      {
        id: 6,
        suit: "diamonds",
        name: 7,
        value: 7,
      },
      {
        id: 7,
        suit: "diamonds",
        name: 8,
        value: 8,
      },
      {
        id: 8,
        suit: "diamonds",
        name: 9,
        value: 9,
      },
      {
        id: 9,
        suit: "diamonds",
        name: 10,
        value: 10,
      },
      {
        id: 10,
        suit: "diamonds",
        name: "J",
        value: 10,
      },
      {
        id: 11,
        suit: "diamonds",
        name: "Q",
        value: 10,
      },
      {
        id: 12,
        suit: "diamonds",
        name: "K",
        value: 10,
      },
      {
        id: 13,
        suit: "diamonds",
        name: "A",
        value: 11,
      },
    ],
  },
  {
    id: 4,
    spades: [
      {
        id: 1,
        suit: "spades",
        name: 2,
        value: 2,
      },
      {
        id: 2,
        suit: "spades",
        name: 3,
        value: 3,
      },
      {
        id: 3,
        suit: "spades",
        name: 4,
        value: 4,
      },
      {
        id: 4,
        suit: "spades",
        name: 5,
        value: 5,
      },
      {
        id: 5,
        suit: "spades",
        name: 6,
        value: 6,
      },
      {
        id: 6,
        suit: "spades",
        name: 7,
        value: 7,
      },
      {
        id: 7,
        suit: "spades",
        name: 8,
        value: 8,
      },
      {
        id: 8,
        suit: "spades",
        name: 9,
        value: 9,
      },
      {
        id: 9,
        suit: "spades",
        name: 10,
        value: 10,
      },
      {
        id: 10,
        suit: "spades",
        name: "J",
        value: 10,
      },
      {
        id: 11,
        suit: "spades",
        name: "Q",
        value: 10,
      },
      {
        id: 12,
        suit: "spades",
        name: "K",
        value: 10,
      },
      {
        id: 13,
        suit: "spades",
        name: "A",
        value: 11,
      },
    ],
  },
];
